Repository odoo/documentation, pull requests merged in 2020-01, with the labels that each got.

#489 13.0 helpdesk kbr
  helpdesk.rst
  helpdesk/close_tickets.rst
  helpdesk/media/closetickets1.png
  helpdesk/media/closetickets2.png
  helpdesk/media/closetickets3.png
  helpdesk/media/closetickets4.png
  helpdesk/media/closetickets5.png
  helpdesk/media/reinvoice_time1.png
  helpdesk/media/reinvoice_time2.png
  helpdesk/media/reinvoice_time3.png
  helpdesk/reinvoice_from_project.rst
Labels: RD

#485 [ADD] payment_payfort configuration
  ecommerce/shopper_experience.rst
  ecommerce/shopper_experience/media/payfort_security_settings.png
  ecommerce/shopper_experience/media/payfort_url_config.png
  ecommerce/shopper_experience/payfort.rst
  ecommerce/shopper_experience/payment.rst
Labels: RD

#500 [IMP] sale_amazon: add information about compliance with Amazon's sec…
  sales/sale_amazon.rst
  sales/sale_amazon/apply.rst
  sales/sale_amazon/manage.rst
  sales/sale_amazon/setup.rst
Labels: RD

#513 [ADD] FSM docs
  _static/banners/fsm.jpg
  applications.rst
  fsm.rst
  fsm/create_quotations.rst
  fsm/customize_worksheets.rst
  fsm/invoicing_time.rst
  fsm/keep_track.rst
  fsm/manage_employees_schedule.rst
  fsm/media/cc1.png
  fsm/media/cc2.png
  fsm/media/cc3.png
  fsm/media/cq1.png
  fsm/media/cq2.png
  fsm/media/cq3.png
  fsm/media/im1.png
  fsm/media/im2.png
  fsm/media/im3.png
  fsm/media/im4.png
  fsm/media/im5.png
  fsm/media/kts1.png
  fsm/media/kts2.png
  fsm/media/mw1.png
  fsm/media/mw2.png
  fsm/media/mw3.png
  fsm/media/onsite1.png
  fsm/media/onsite2.png
  fsm/media/plit1.png
  fsm/media/plit2.png
  fsm/media/plit3.png
  fsm/media/plit4.png
  fsm/media/po1.png
  fsm/media/po2.png
  fsm/onsite_tasks_from_sales_orders.rst
  fsm/plan_onsite.rst
  fsm/planning_itinerary.rst
Labels: RD

#515 [ADD] Planning docs
  _static/banners/planning.jpg
  applications.rst
  planning.rst
  planning/duplicate_a_planning.rst
  planning/media/cs1.png
  planning/media/cs2.png
  planning/media/cs3.png
  planning/media/cs4.png
  planning/media/sp1.png
  planning/media/sp2.png
  planning/media/sp3.png
  planning/media/sp4.png
  planning/send_planned_shifts.rst
Labels: RD

#496 [ADD] : l10n_ar Localization user documentation
  accounting/localizations.rst
  accounting/localizations/argentina.rst
  accounting/localizations/media/argentina01.png
  accounting/localizations/media/argentina02.png
  accounting/localizations/media/argentina03.png
  accounting/localizations/media/argentina04.png
  accounting/localizations/media/argentina05.png
  accounting/localizations/media/argentina06.png
  accounting/localizations/media/argentina07.png
  accounting/localizations/media/argentina08.png
  accounting/localizations/media/argentina09.png
  accounting/localizations/media/argentina10.png
  accounting/localizations/media/argentina11.png
  accounting/localizations/media/argentina12.png
  accounting/localizations/media/argentina13.png
  accounting/localizations/media/argentina14.png
  accounting/localizations/media/argentina15.png
  accounting/localizations/media/argentina16.png
  accounting/localizations/media/argentina17.png
  accounting/localizations/media/argentina18.png
  accounting/localizations/media/argentina19.png
  accounting/localizations/media/argentina20.png
  accounting/localizations/media/argentina21.png
  accounting/localizations/media/argentina22.png
  accounting/localizations/media/argentina23.png
  accounting/localizations/media/colombia_ubl2.1_1.png
  accounting/localizations/media/colombia_ubl2.1_10.png
  accounting/localizations/media/colombia_ubl2.1_11.png
  accounting/localizations/media/colombia_ubl2.1_12.png
  accounting/localizations/media/colombia_ubl2.1_13.png
  accounting/localizations/media/colombia_ubl2.1_14.png
  accounting/localizations/media/colombia_ubl2.1_15.png
  accounting/localizations/media/colombia_ubl2.1_16.png
  accounting/localizations/media/colombia_ubl2.1_17.png
  accounting/localizations/media/colombia_ubl2.1_18.png
  accounting/localizations/media/colombia_ubl2.1_2.png
  accounting/localizations/media/colombia_ubl2.1_3.png
  accounting/localizations/media/colombia_ubl2.1_4.png
  accounting/localizations/media/colombia_ubl2.1_5.png
  accounting/localizations/media/colombia_ubl2.1_6.png
  accounting/localizations/media/colombia_ubl2.1_7.png
  accounting/localizations/media/colombia_ubl2.1_8.png
  accounting/localizations/media/colombia_ubl2.1_9.png
Labels: RD

#522 Update usage.rst
  inventory/management/products/usage.rst
Labels: content issue

#523 [IMP] sale_amazon: correct some form answers
  sales/amazon_connector/apply.rst
Labels: RD

#521 [ADD] add a new documentation about deferred expenses (accounting)
  accounting/payables/supplier_bills.rst
  accounting/payables/supplier_bills/deferred_expenses.rst
  accounting/payables/supplier_bills/media/deferred_expenses01.png
  accounting/payables/supplier_bills/media/deferred_expenses02.png
  accounting/payables/supplier_bills/media/deferred_expenses03.png
  accounting/payables/supplier_bills/media/deferred_expenses04.png
  accounting/payables/supplier_bills/media/deferred_expenses05.png
  accounting/payables/supplier_bills/media/deferred_expenses06.png
  accounting/payables/supplier_bills/media/deferred_expenses07.png
  accounting/payables/supplier_bills/media/deferred_expenses08.png
  accounting/payables/supplier_bills/media/deferred_expenses09.png
Labels: RD

#525 Improve VOIP User Doc
  crm/optimize/media/voip_config01.png
  crm/optimize/media/voip_config02.png
  crm/optimize/setup.rst
Labels: OE, content issue

#472 [REM] Remove probable turnover
  crm/performance.rst
  crm/performance/turnover.rst
Labels: content issue

#530 [IMP] accounting: correct a small mistake in Deferred Expenses and De…
  accounting/payables/supplier_bills/deferred_expenses.rst
  accounting/receivables/customer_invoices/deferred_revenues.rst
Labels: RD

#534 [IMP] discuss: added note about config of outbound server
  discuss/email_servers.rst
Labels: RD

#529 [REV] pos: revert doc for ingenico and six
  point_of_sale/payment.rst
  point_of_sale/payment/ingenico.rst
  point_of_sale/payment/six.rst
Labels: RD

#532 [FIX] fix broken image
  sales/send_quotations/media/terms_and_conditions03.png
  sales/send_quotations/media/terms_and_conditions04.png
  sales/send_quotations/terms_and_conditions.rst
Labels: RD

#460 [IMP] taxcloud: coupon nightmare
  accounting/others/taxes/taxcloud.rst
Labels: content improvement

#538 [IMP] amazon_connector: add caution for secondary form
  sales/amazon_connector/apply.rst
  sales/amazon_connector/setup.rst
Labels: content improvement
