Repository odoo/documentation, pull requests merged in 2020-03, with the labels that each got.

#584 [ADD] crm: doc about partner autocomplete
  crm/optimize.rst
  crm/optimize/media/odoo_autocomplete.png
  crm/optimize/media/odoo_info_autocomplete.png
  crm/optimize/media/settings_partner_autocomplete.png
  crm/optimize/partner_autocomplete.rst
Labels: content improvement

#586 Replace recommended uuid generator with open source version
  db_management/db_premise.rst
  locale/ar/LC_MESSAGES/db_management.po
  locale/da/LC_MESSAGES/db_management.po
  locale/de/LC_MESSAGES/db_management.po
  locale/es/LC_MESSAGES/db_management.po
  locale/fr/LC_MESSAGES/db_management.po
  locale/it/LC_MESSAGES/db_management.po
  locale/nl/LC_MESSAGES/db_management.po
  locale/pt_BR/LC_MESSAGES/db_management.po
  locale/ru/LC_MESSAGES/db_management.po
  locale/sources/db_management.pot
  locale/tr/LC_MESSAGES/db_management.po
  locale/uk/LC_MESSAGES/db_management.po
  locale/zh_CN/LC_MESSAGES/db_management.po
Labels: community, content improvement

#590 [ADD] general: debug doc + link to the file on mentions over other apps
  accounting/bank/feeds/bank_synchronization.rst
  accounting/localizations/colombia.rst
  accounting/localizations/france.rst
  accounting/localizations/mexico.rst
  accounting/others/reporting/customize.rst
  accounting/others/reporting/media/customize01.png
  accounting/others/reporting/media/customize03.png
  discuss/email_servers.rst
  discuss/media/developer_mode.png
  ecommerce/shopper_experience/payment.rst
  general.rst
  general/developer_mode.rst
  general/developer_mode/activate.rst
  general/developer_mode/media/button_location.png
  general/developer_mode/media/monkey.png
  general/developer_mode/media/settings.png
  general/developer_mode/media/url.png
  general/in_app_purchase/in_app_purchase.rst
  helpdesk/getting_started.rst
  helpdesk/media/helpdesk04.png
  inventory/barcode/operations/barcode_nomenclature.rst
  inventory/management/planning/media/schedulers_02.png
  inventory/management/planning/schedulers.rst
  inventory/management/reporting/inventory_valuation_config.rst
  odoo_sh/getting_started/create.rst
  odoo_sh/getting_started/first_module.rst
  odoo_sh/getting_started/media/firstmodule-test-developermode.png
  point_of_sale/advanced/media/mercury02.png
  point_of_sale/advanced/mercury.rst
  sales/amazon_connector/manage.rst
  sales/amazon_connector/setup.rst
  sales/ebay_connector/setup.rst
  sms_marketing/overview/integrations_and_template.rst
  sms_marketing/pricing/pricing_and_faq.rst
  social_marketing/social_marketing/social_marketing.rst
  website/optimize/seo.rst
Labels: content improvement

#575 [MOV] Accounting: create a new "Fiscality" section
  accounting.rst
  accounting/fiscality.rst
  accounting/fiscality/fiscal_year.rst
  accounting/fiscality/fiscal_year/close_fiscal_year.rst
  accounting/fiscality/fiscal_year/fiscal_year.rst
  accounting/fiscality/fiscal_year/media/close_fiscal_year01.png
  accounting/fiscality/fiscal_year/media/fiscal_year01.png
  accounting/fiscality/fiscal_year/media/fiscal_year02.png
  accounting/fiscality/fiscal_year/media/fiscal_year03.png
  accounting/fiscality/taxes.rst
  accounting/fiscality/taxes/B2B_B2C.rst
  accounting/fiscality/taxes/application.rst
  accounting/fiscality/taxes/cash_basis_taxes.rst
  accounting/fiscality/taxes/create.rst
  accounting/fiscality/taxes/default_taxes.rst
  accounting/fiscality/taxes/media/application01.png
  accounting/fiscality/taxes/media/application02.png
  accounting/fiscality/taxes/media/application03.png
  accounting/fiscality/taxes/media/application04.png
  accounting/fiscality/taxes/media/application05.png
  accounting/fiscality/taxes/media/cash_basis_taxes01.png
  accounting/fiscality/taxes/media/cash_basis_taxes02.png
  accounting/fiscality/taxes/media/cash_basis_taxes03.png
  accounting/fiscality/taxes/media/create01.png
  accounting/fiscality/taxes/media/create02.png
  accounting/fiscality/taxes/media/create04.png
  accounting/fiscality/taxes/media/price_B2C_B2B01.png
  accounting/fiscality/taxes/media/price_B2C_B2B02.png
  accounting/fiscality/taxes/media/price_B2C_B2B03.png
  accounting/fiscality/taxes/media/price_B2C_B2B04.png
  accounting/fiscality/taxes/media/price_B2C_B2B05.png
  accounting/fiscality/taxes/media/retention01.png
  accounting/fiscality/taxes/media/retention02.png
  accounting/fiscality/taxes/media/retention03.png
  accounting/fiscality/taxes/media/retention04.png
  accounting/fiscality/taxes/media/tax_included.png
  accounting/fiscality/taxes/media/taxcloud01.png
  accounting/fiscality/taxes/media/taxcloud02.png
  accounting/fiscality/taxes/media/taxcloud03.png
  accounting/fiscality/taxes/media/taxcloud04.png
  accounting/fiscality/taxes/retention.rst
  accounting/fiscality/taxes/tax_included.rst
  accounting/fiscality/taxes/taxcloud.rst
  accounting/others.rst
  accounting/others/adviser.rst
  accounting/others/configuration.rst
  ecommerce/taxes.rst
  expense/expense.rst
  sales/products_prices/taxes.rst
Labels: content improvement

#591 [IMP] general: quick adjustment on developer mode doc
  general/developer_mode/activate.rst
Labels: content improvement

#596 [FIX] Unsubscribe button 403 reason explanation
  email_marketing/overview/manage_unsubscriptions.rst
Labels: content issue

#561 [FIX] On-premise GeoIp installation
  ecommerce/publish.rst
  website/publish/media/on-premise_geo-ip-installation01.png
  website/publish/multi_website.rst
  website/publish/on-premise_geo-ip-installation.rst
Labels: content improvement

#594 [ADD] l10n_ar_edi: Electronic Invoice functional guide for Argentina
  accounting/localizations/argentina.rst
  accounting/localizations/media/argentina01.png
  accounting/localizations/media/argentina_edi_01.png
  accounting/localizations/media/argentina_edi_02.png
  accounting/localizations/media/argentina_edi_03.png
  accounting/localizations/media/argentina_edi_04.png
  accounting/localizations/media/argentina_edi_05.png
  accounting/localizations/media/argentina_edi_06.png
  accounting/localizations/media/argentina_edi_07.png
  accounting/localizations/media/argentina_edi_08.png
  accounting/localizations/media/argentina_edi_09.png
  accounting/localizations/media/argentina_edi_10.png
  accounting/localizations/media/argentina_edi_11.png
  accounting/localizations/media/argentina_edi_12.png
  accounting/localizations/media/argentina_edi_13.png
  accounting/localizations/media/argentina_edi_14.png
  accounting/localizations/media/argentina_edi_15.png
  accounting/localizations/media/argentina_edi_16.png
  accounting/localizations/media/argentina_edi_17.png
  accounting/localizations/media/argentina_edi_18.png
  accounting/localizations/media/argentina_edi_19.png
  accounting/localizations/media/argentina_edi_20.png
  accounting/localizations/media/argentina_edi_21.png
  accounting/localizations/media/argentina_edi_22.png
  accounting/localizations/media/argentina_edi_23.png
  accounting/localizations/media/argentina_edi_24.png
Labels: content improvement

#573 [IMP] accounting: new version of Payment Terms
  accounting/receivables/customer_invoices.rst
  accounting/receivables/customer_invoices/installment_plans.rst
  accounting/receivables/customer_invoices/media/installment01.png
  accounting/receivables/customer_invoices/media/payment_terms_configuration.png
  accounting/receivables/customer_invoices/media/payment_terms_journal_entry.png
  accounting/receivables/customer_invoices/payment_terms.rst
Labels: content improvement

#587 [ADD] accounting: doc about snailmail
  accounting/receivables/customer_invoices.rst
  accounting/receivables/customer_invoices/media/invoice_bypost.png
  accounting/receivables/customer_invoices/media/setup_snailmail.png
  accounting/receivables/customer_invoices/snailmail.rst
Labels: content improvement

#578 [ADD] social_marketing: improved and added documentation
  social_marketing.rst
  social_marketing/overview.rst
  social_marketing/overview/campaigns.rst
  social_marketing/overview/livechat.rst
  social_marketing/overview/manage_social.rst
  social_marketing/overview/media/add_linkedin.png
  social_marketing/overview/media/add_streams.png
  social_marketing/overview/media/calendar_view.png
  social_marketing/overview/media/create_campaign.png
  social_marketing/overview/media/enable_livechat.png
  social_marketing/overview/media/enable_push.png
  social_marketing/overview/media/feed.png
  social_marketing/overview/media/individually_push.png
  social_marketing/overview/media/insights.png
  social_marketing/overview/media/monitor_visitors.png
  social_marketing/overview/media/publish_content.png
  social_marketing/overview/media/push_permission.png
  social_marketing/overview/media/push_rules.png
  social_marketing/overview/media/push_to_a_group.png
  social_marketing/overview/media/website_track_pages.png
  social_marketing/overview/push_notifications.rst
  social_marketing/social_marketing.rst
  social_marketing/social_marketing/media/social_marketing01.png
  social_marketing/social_marketing/media/social_marketing02.png
  social_marketing/social_marketing/media/social_marketing03.png
  social_marketing/social_marketing/media/social_marketing04.png
  social_marketing/social_marketing/media/social_marketing05.png
  social_marketing/social_marketing/social_marketing.rst
Labels: content improvement

#569 [ADD] Accounting: Bank Statements and remove old documentation
  accounting/bank/feeds.rst
  accounting/bank/feeds/bank_statements.rst
  accounting/bank/feeds/bank_synchronization.rst
  accounting/bank/feeds/coda.rst
  accounting/bank/feeds/manual.rst
  accounting/bank/feeds/media/bank_statements01.png
  accounting/bank/feeds/media/bank_statements02.png
  accounting/bank/feeds/media/bank_statements03.png
  accounting/bank/feeds/media/coda01.png
  accounting/bank/feeds/media/coda02.png
  accounting/bank/feeds/media/coda03.png
  accounting/bank/feeds/media/manual01.png
  accounting/bank/feeds/media/manual02.png
  accounting/bank/feeds/media/manual03.png
  accounting/bank/feeds/media/manual04.png
  accounting/bank/feeds/media/manual05.png
  accounting/bank/feeds/media/manual06.png
  accounting/bank/feeds/media/manual07.png
  accounting/bank/feeds/media/manual08.png
  accounting/bank/feeds/media/manual09.png
  accounting/bank/feeds/media/manual10.png
  accounting/bank/feeds/media/ofx01.png
  accounting/bank/feeds/media/ofx02.png
  accounting/bank/feeds/media/ofx03.png
  accounting/bank/feeds/media/ofx04.png
  accounting/bank/feeds/media/qif01.png
  accounting/bank/feeds/media/qif02.png
  accounting/bank/feeds/media/qif03.png
  accounting/bank/feeds/media/qif04.png
  accounting/bank/feeds/ofx.rst
  accounting/bank/feeds/qif.rst
  accounting/bank/reconciliation/configure.rst
  accounting/bank/reconciliation/use_cases.rst
Labels: content improvement

#583 [IMP] project: documentation overhaul 2
  project/advanced.rst
  project/advanced/feedback.rst
  project/advanced/media/customer_rating.png
  project/advanced/media/feedback01.png
  project/advanced/media/feedback02.png
  project/advanced/media/feedback03.png
  project/advanced/media/feedback04.png
  project/advanced/media/feedback05.png
  project/advanced/media/feedback06.png
  project/advanced/media/feedback07.png
  project/advanced/media/feedback08.png
  project/advanced/media/feedback09.png
  project/advanced/media/feedback10.png
  project/advanced/media/hours_profitability.png
  project/advanced/media/not_timesheet_installed.png
  project/advanced/media/percentage_happy.png
  project/advanced/media/rating_chatter.png
  project/advanced/media/rating_project.png
  project/advanced/media/rating_report.png
  project/advanced/media/rating_template.png
  project/advanced/media/reporting.png
  project/advanced/media/timesheet_instaled.png
  project/advanced/profitability.rst
  project/planning.rst
  project/planning/assignments.rst
  project/planning/forecast.rst
  project/planning/media/allocate_time.png
  project/planning/media/assignments01.png
  project/planning/media/assignments02.png
  project/planning/media/assignments03.png
  project/planning/media/assignments04.png
  project/planning/media/assignments06.png
  project/planning/media/assignments07.png
  project/planning/media/assignments08.png
  project/planning/media/assignments09.png
  project/planning/media/assignments10.png
  project/planning/media/compare_forecast.png
  project/planning/media/enable_timesheets.png
  project/planning/media/forecast01.png
  project/planning/media/forecast02.png
  project/planning/media/forecast03.png
  project/planning/media/forecast04.png
  project/planning/media/forecast05.png
  project/planning/media/forecast06.png
  project/planning/media/forecast07.png
  project/planning/media/planning_project.png
Labels: content improvement

#574 [ADD] general: doc about tags
  general.rst
  general/tags.rst
  general/tags/media/create_tags.png
  general/tags/media/create_tags_fly.png
  general/tags/media/delete.png
  general/tags/media/mkt_automation.png
  general/tags/media/reporting.png
  general/tags/media/tags_colors.png
  general/tags/take_tags.rst
Labels: content improvement

#597 [ADD] accounting: new documentation about synchronization with Ponto
  accounting/bank/feeds.rst
  accounting/bank/feeds/bank_synchronization.rst
  accounting/bank/feeds/media/ponto_add_bank.png
  accounting/bank/feeds/media/ponto_link_odoo.png
  accounting/bank/feeds/media/ponto_logo.png
  accounting/bank/feeds/media/ponto_organization.png
  accounting/bank/feeds/media/ponto_synchronization.png
  accounting/bank/feeds/ponto.rst
Labels: content improvement

#595 [IMP] Accounting: add new version of Accounting/Invoicing initial setup
  accounting/overview/getting_started/media/setup01.png
  accounting/overview/getting_started/media/setup02.png
  accounting/overview/getting_started/media/setup_accounting_onboarding.png
  accounting/overview/getting_started/media/setup_chart_of_accounts.png
  accounting/overview/getting_started/media/setup_company.png
  accounting/overview/getting_started/media/setup_document_layout.png
  accounting/overview/getting_started/media/setup_invoicing_onboarding.png
  accounting/overview/getting_started/setup.rst
Labels: content improvement

#599 [MOV] accounting: remove "how to...?" from the titles
  accounting/bank/feeds/paypal.rst
  accounting/bank/misc/batch.rst
  accounting/bank/misc/interbank.rst
  accounting/bank/reconciliation/use_cases.rst
  accounting/bank/setup/create_bank_account.rst
  accounting/bank/setup/foreign_currency.rst
  accounting/bank/setup/manage_cash_register.rst
  accounting/fiscality/fiscal_year/close_fiscal_year.rst
  accounting/fiscality/taxes.rst
  accounting/fiscality/taxes/B2B_B2C.rst
  accounting/fiscality/taxes/application.rst
  accounting/fiscality/taxes/cash_basis_taxes.rst
  accounting/fiscality/taxes/create.rst
  accounting/fiscality/taxes/default_taxes.rst
  accounting/fiscality/taxes/retention.rst
  accounting/fiscality/taxes/tax_included.rst
  accounting/fiscality/taxes/taxcloud.rst
  accounting/others.rst
  accounting/others/adviser/budget.rst
  accounting/others/analytic/purchases_expenses.rst
  accounting/others/analytic/timesheets.rst
  accounting/others/multicurrencies/how_it_works.rst
  accounting/others/multicurrencies/invoices_payments.rst
  accounting/others/reporting/customize.rst
  accounting/others/reporting/main_reports.rst
  accounting/payables/misc/employee_expense.rst
  accounting/payables/misc/forecast.rst
  accounting/payables/pay/multiple.rst
  accounting/payables/supplier_bills/bills_or_receipts.rst
  accounting/payables/supplier_bills/manage.rst
  accounting/receivables/customer_payments/check.rst
  accounting/receivables/customer_payments/credit_cards.rst
  accounting/receivables/customer_payments/recording.rst
Labels: content improvement

#576 [ADD] general: doc about google spreadsheets in odoo
  general/auth.rst
  general/auth/google_spreadsheets.rst
  general/auth/media/add_to_google_spread.png
  general/auth/media/authori.png
  general/auth/media/odoo_menu.png
  general/auth/media/retrieve_data.png
  general/auth/media/retrieve_sums.png
Labels: content improvement

#606 [ADD] accounting: add new doc about tax/vat returns
  accounting/fiscality/taxes.rst
  accounting/fiscality/taxes/media/tax_return_closing.png
  accounting/fiscality/taxes/media/tax_return_grids.png
  accounting/fiscality/taxes/media/tax_return_lock.png
  accounting/fiscality/taxes/media/tax_return_overview.png
  accounting/fiscality/taxes/media/tax_return_periodicity.png
  accounting/fiscality/taxes/media/tax_return_report.png
  accounting/fiscality/taxes/media/tax_return_taxes.png
  accounting/fiscality/taxes/tax_returns.rst
Labels: content improvement

#603 [ADD] Point of Sale: New doc about fiscal positions
  point_of_sale/restaurant.rst
  point_of_sale/restaurant/fiscal_position.rst
  point_of_sale/restaurant/media/fiscal_position_01.png
  point_of_sale/restaurant/media/fiscal_position_02.png
  point_of_sale/restaurant/media/fiscal_position_03.png
  point_of_sale/restaurant/media/fiscal_position_04.png
Labels: content improvement

#604 [ADD] Point of Sale: New doc about pricelists
  point_of_sale/advanced_pricing_features.rst
  point_of_sale/advanced_pricing_features/media/pricelists_01.png
  point_of_sale/advanced_pricing_features/media/pricelists_02.png
  point_of_sale/advanced_pricing_features/media/pricelists_03.png
  point_of_sale/advanced_pricing_features/media/pricelists_04.png
  point_of_sale/advanced_pricing_features/pricelists.rst
Labels: content improvement

#558 [IMP] update content of "Invoicing policy" (Sales - V13)
  sales/invoicing/invoicing_policy.rst
  sales/invoicing/media/invoicing_policy01.png
  sales/invoicing/media/invoicing_policy02.png
  sales/invoicing/media/invoicing_policy_1.png
  sales/invoicing/media/invoicing_policy_2.png
  sales/invoicing/media/invoicing_policy_3.png
  sales/invoicing/media/invoicing_policy_4.png
  sales/invoicing/media/invoicing_policy_5.png
Labels: content improvement

#563 [ADD] survey: documentation
  _static/banners/survey.png
  applications.rst
  survey.rst
  survey/overview.rst
  survey/overview/create.rst
  survey/overview/media/sur1.png
  survey/overview/media/sur2.png
  survey/overview/media/sur3.png
Labels: content improvement

#556 [IMP] update content of "Terms & conditions" (Sales - V13)
  sales/send_quotations/media/terms_and_conditions01.png
  sales/send_quotations/media/terms_and_conditions02.png
  sales/send_quotations/media/terms_and_conditions03.png
  sales/send_quotations/media/terms_and_conditions04.png
  sales/send_quotations/media/terms_conditions_1.png
  sales/send_quotations/media/terms_conditions_2.png
  sales/send_quotations/media/terms_conditions_3.png
  sales/send_quotations/media/terms_conditions_4.png
  sales/send_quotations/media/terms_conditions_5.png
  sales/send_quotations/media/terms_conditions_6.png
  sales/send_quotations/media/terms_conditions_7.png
  sales/send_quotations/terms_and_conditions.rst
Labels: content improvement

#601 [IMP] live_chat: overhaul documentation update
  applications.rst
  live_chat.rst
  livechat/livechat.rst
  livechat/media/live_chat01.png
  livechat/media/live_chat02.png
  livechat/media/live_chat03.png
  livechat/media/live_chat04.png
  livechat/media/live_chat05.png
  livechat/media/live_chat06.png
  livechat/media/live_chat07.png
  livechat/overview.rst
  livechat/overview/get_started.rst
  livechat/overview/media/canned_response.png
  livechat/overview/media/channels.png
  livechat/overview/media/create_ticket.png
  livechat/overview/media/customer_ratings.png
  livechat/overview/media/discuss.png
  livechat/overview/media/joinchannel.png
  livechat/overview/media/livechat_settings.png
  livechat/overview/media/operator_chatwindow.png
  livechat/overview/media/publish_ratings.png
  livechat/overview/media/rules.png
  livechat/overview/media/user_chatwindow.png
  livechat/overview/media/widget.png
  livechat/overview/ratings.rst
  livechat/overview/responses.rst
  social_marketing/overview/livechat.rst
Labels: content improvement

#585 [ADD] accounting: doc about OCR
  accounting/payables/supplier_bills.rst
  accounting/payables/supplier_bills/media/example_ocr.png
  accounting/payables/supplier_bills/media/setup_ocr.png
  accounting/payables/supplier_bills/ocr.rst
Labels: content improvement

#612 [MOV] Point of Sale: Doc moves
  point_of_sale.rst
  point_of_sale/advanced.rst
  point_of_sale/advanced/media/mercury01.png
  point_of_sale/advanced/media/mercury03.png
  point_of_sale/advanced/media/mercury04.png
  point_of_sale/advanced/mercury.rst
  point_of_sale/shop.rst
  point_of_sale/shop/barcode.rst
  point_of_sale/shop/cash_rounding.rst
  point_of_sale/shop/media/barcode01.png
  point_of_sale/shop/media/barcode02.png
  point_of_sale/shop/media/cash_rounding01.png
  point_of_sale/shop/media/cash_rounding02.png
  point_of_sale/shop/media/cash_rounding03.png
  point_of_sale/shop/media/multicashiers01.png
  point_of_sale/shop/media/multicashiers02.png
  point_of_sale/shop/media/multicashiers03.png
  point_of_sale/shop/media/multicashiers04.png
  point_of_sale/shop/media/multicashiers05.png
  point_of_sale/shop/media/multicashiers06.png
  point_of_sale/shop/media/multicashiers07.png
  point_of_sale/shop/media/reprint01.png
  point_of_sale/shop/media/reprint02.png
  point_of_sale/shop/media/reprint03.png
  point_of_sale/shop/multicashiers.rst
  point_of_sale/shop/reprint.rst
Labels: content improvement
